### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cmnord** [jessamynsmith/flask-google-sheets#1]
Hello, thanks for writing this! I'd like to use it for a project for a school club. Can you [add a license](https://choosealicense.com/) to the project so I know how to use this code fairly? If it's easier for you, I can make a pull request to add the license of your choice.

**Comment by jessamynsmith** [comment]
Oh sure! I'd be happy to. I normally do MIT so I'll copy that from one of
my other projects.

**Comment by jessamynsmith** [comment]
License added, as requested. See 7bbcdbba096eda241e3c378366c39464e98fc6e3
